{{- if and .Values.services.ui.enabled .Values.services.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ui.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  {{- with .Values.services.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.services.ui.ingress.className }}
  ingressClassName: {{ .Values.services.ui.ingress.className }}
  {{- end }}
  {{- if .Values.services.ui.ingress.tls }}
  tls:
    {{- range .Values.services.ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.services.ui.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ui.fullname" . }}
                port:
                  number: {{ .Values.services.ui.service.port }}
{{- end }}
